#!/usr/bin/python
#
#    testdrive-select-iso - present a list and select an ISO for testdriving
#    Copyright (C) 2009 Canonical Ltd.
#    Copyright (C) 2009 Dustin Kirkland
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


import commands, time, os

PKG = "testdrive"
VT = commands.getoutput("kvm-ok >/dev/null 2>&1 && echo 1 || echo 0")
if VT == "0":
	ARCH = "i386"
else:
	ARCH = commands.getoutput("uname -m | grep -qs x86_64 && echo amd64 || echo i386")
#RELEASE = "lucid"

ISO = []
ISO.append({"name":"Fedora Desktop (%s)"%ARCH, "url":"http://alt.fedoraproject.org/pub/alt/nightly-composes/desktop/desktop-%s-20100211.17.iso"%(ARCH)})
ISO.append({"name":"Fedora XFCE Spin (%s)"%ARCH, "url":"http://alt.fedoraproject.org/pub/alt/nightly-composes/xfce/xfce-%s-20100212.17.iso"%(ARCH)})
ISO.append({"name":"Fedora LXDE Spin (%s)"%ARCH, "url":"http://alt.fedoraproject.org/pub/alt/nightly-composes/lxde/lxde-%s-20100212.17.iso"%(ARCH)})
ISO.append({"name":"Fedora KDE Spin (%s)"%ARCH, "url":"http://alt.fedoraproject.org/pub/alt/nightly-composes/kde/kde-%s-20100212.17.iso"%(ARCH)})
if ARCH == "amd64":
	arch = "i386"
	ISO.append({"name":"Fedora Desktop (%s)"%ARCH, "url":"http://alt.fedoraproject.org/pub/alt/nightly-composes/desktop/desktop-%s-20100211.17.iso"%(ARCH)})
	ISO.append({"name":"Fedora XFCE Spin (%s)"%ARCH, "url":"http://alt.fedoraproject.org/pub/alt/nightly-composes/xfce/xfce-%s-20100212.17.iso"%(ARCH)})
	ISO.append({"name":"Fedora LXDE Spin (%s)"%ARCH, "url":"http://alt.fedoraproject.org/pub/alt/nightly-composes/lxde/lxde-%s-20100212.17.iso"%(ARCH)})
	ISO.append({"name":"Fedora KDE Spin (%s)"%ARCH, "url":"http://alt.fedoraproject.org/pub/alt/nightly-composes/kde/kde-%s-20100212.17.iso"%(ARCH)})

#ISO.append({"name":"Ubuntu Netbook", "url":"rsync://cdimage.ubuntu.com/cdimage/ubuntu-netbook/daily-live/current/%s-netbook-i386.iso"%(RELEASE)})

# These are problematic, because the names are all the same ... lucid-desktop-i386.iso
# Need to rename the destination ISO accordingly
#rsync://cdimage.ubuntu.com/cdimage/kubuntu/daily-live/current/%s-desktop-%s.iso
#rsync://cdimage.ubuntu.com/cdimage/xubuntu/daily-live/current/%s-desktop-%s.iso
#rsync://cdimage.ubuntu.com/cdimage/mythbuntu/daily-live/current/%s-desktop-%s.iso
#rsync://cdimage.ubuntu.com/cdimage/kubuntu-netbook/daily-live/current/%s-netbook-i386.iso"

while 1:
	i = 1
	print("\nWitamy w Testdrive!\n")
	for iso in ISO:
		print("  %d. %s (%s)" % (i, iso["name"], RELEASE))
		filename = os.path.basename(iso["url"])
		path = "%s/.cache/%s/iso/%s" % (os.environ["HOME"], PKG, filename)
		if os.path.exists(path):
			print("     +-cache--> [%s] %s" % (time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(os.path.getmtime(path))), filename))
		i=i+1
	print("  %d. Other (prompt for ISO URL)" % i)

	try:
		input = raw_input("\nWybierz obraz ISO do przetestowania: ")
		choice = int(input)
	except KeyboardInterrupt:
		print("\n")
		exit(0)
	except:
		print("\nERROR: Błędne dane.\n")
		continue

	if choice == i:
		url = raw_input("\nWpisz adres URL do pliku ISO: ")
		break
	elif choice in range(1, i):
		url = ISO[choice-1]["url"]
		break
	else:
		print("\nERROR: Błędna sekcja.\n")

os.system("testdrive -u %s" % url)
