.TH testdrive 1 "5 Nov 2009" testdrive "testdrive"
.SH NAME
testdrive \- Test Drive the current Ubuntu Development Snapshot in a VM

.SH SYNOPSIS
testdrive [-f FILE] [-u URL]

.SH OPTIONS
\fB\-f FILE\fP - path to a configuration file to read

\fB\-u URL\fP - url to an ISO image to download and use; can be [rsync|http|ftp|file] protocol

.SH DESCRIPTION
\fBtestdrive\fP is a utility that allows you to easily download the latest Ubuntu development release and run it in a KVM virtual machine.

The global configuration file, \fI/etc/testdriverc\fP, is sourced first, followed by the user's local configuration file, \fI~/.testdriverc\fP, and xdg configuration \fI~/.config/testdrive/testdriverc\fP.

Users wanting to change the behavior default configuration can make a copy of the global configuration \fI/etc/testdriverc\fP, and either store it as \fI~/.testdriverc\fP, or as another file and pass that filename on the command line.

Downloaded ISO files and disk images are stored in \fI~/.cache/testdrive\fP, and may optionally be cleaned out, periodically.

.SH FILES
\fI/etc/testdriverc\fP, \fI~/.testdriverc\fP, \fI~/.config/testdrive/testdriverc\fP, \fI~/.cache/testdrive\fP

.SH LINKS
.TP
\fIhttp://launchpad.net/testdrive\fP
.PD

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@canonical.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
