.TH testdrive-select-iso 1 "26 Nov 2009" testdrive "testdrive"
.SH NAME
testdrive\-select\-iso \- select an ISO test testdrive, and then launch testdrive

.SH SYNOPSIS
testdrive\-select\-iso

.SH DESCRIPTION
This utility will prompt the user to choose from one of a few ISOs, and then launch testdrive against that ISO.  It will also note which have locally cached copies.

.SH SEE ALSO
\fBtestdrive\fP(1)

.SH LINKS
.TP
\fIhttp://launchpad.net/testdrive\fP
.PD

.SH AUTHOR
This manpage and the utility was written by Dustin Kirkland <kirkland@canonical.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
